version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Granitos.Api/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Services.Infrastructure/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Services.Domain/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Errors.Core/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Errors.Http/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Errors.Http.FluentValidation/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Errors.FakeApi/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Errors.Http.Tests/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Mongo/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.SecretVault/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.Common.Testing/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
  - package-ecosystem: "nuget"
    directory: "/Granitos.IntegrationTests.FakeApi/"
    schedule:
      interval: "weekly"
    target-branch: "master"
    reviewers:
      - "DiracSpace"
    labels:
      - "dependencies"
